server:
  port: 8080
spring:
  devtools.restart.exclude: static/**,public/**
  datasource:
#    url: jdbc:postgresql://localhost:5432/biblioteca # Production
#    databaseName: biblioteca
#    username: postgres
#    password: postgres
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect # Production
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        format_sql: true
    h2:
      console:
        enabled: true
  thymeleaf:
    mode: html
  messages:
    basename: messages
  resources:
    static-locations: classpath:/static/, file:/static/
liquibase:
  change-log: classpath:db/liquibase-changelog.xml
logging:
  file: app.log
  level:
    root: INFO
    org.springframework.web: INFO
    br.com.frameworks.biblioteca: DEBUG
